CREATE TABLE stripe_event_log (
    id UUID PRIMARY KEY,
    event_id TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE orders
    ADD COLUMN is_digital BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE disputes
    ADD COLUMN return_required BOOLEAN NOT NULL DEFAULT FALSE;
